Class {
	#name : 'JadeServer',
	#superclass : 'Object',
	#instVars : [
		'classList',
		'classOrganizers',
		'readStream',
		'writeStream',
		'selectedClass',
		'methodFilterType',
		'methodFilters',
		'selections'
	],
	#classVars : [
		'AllGroups',
		'AllUsers',
		'ClassOrganizer',
		'ClientForwarder',
		'GemStoneError',
		'Globals',
		'GsMethodDictionary',
		'ProcessorScheduler',
		'SymbolDictionary',
		'SymbolList',
		'System',
		'UserGlobals',
		'UserProfile'
	],
	#category : 'RowanClientServicesClient'
}
