Class {
	#name : 'JadeiteMethodCompiledAnnouncement',
	#superclass : 'Announcement',
	#instVars : [
		'methodService'
	],
	#category : 'Jadeite-TextPanes',
	#package : 'Jadeite-TextPanes'
}

{ #category : 'accessing' }
JadeiteMethodCompiledAnnouncement >> methodService [

	^ methodService
]

{ #category : 'accessing' }
JadeiteMethodCompiledAnnouncement >> methodService: anObject [

	methodService := anObject
]
