Class {
	#name : 'JadeiteUpdateMethodSourceAnnouncement',
	#superclass : 'Announcement',
	#instVars : [
		'scrollOffset'
	],
	#category : 'Jadeite-TextPanes',
	#package : 'Jadeite-TextPanes'
}

{ #category : 'accessing' }
JadeiteUpdateMethodSourceAnnouncement >> scrollOffset [

	^ scrollOffset
]

{ #category : 'accessing' }
JadeiteUpdateMethodSourceAnnouncement >> scrollOffset: anObject [

	scrollOffset := anObject
]
