Extension { #name : 'JadeiteAddPackageDialog' }

{ #category : '*Jadeite-Tests' }
JadeiteAddPackageDialog >> componentNamePresenter [ 

	^componentNamePresenter
]

{ #category : '*Jadeite-Tests' }
JadeiteAddPackageDialog >> componentNamePresenter: aString [
	"for testing"
	componentNamePresenter text: aString
]

{ #category : '*Jadeite-Tests' }
JadeiteAddPackageDialog >> packageNamePresenter: aString [
	"for testing"
	packageNamePresenter text: aString
]
